export const BOARDS=['Principal','Remarketing','Abandonados','Pós-venda'];
export const NICHES=['Serviços','Marketing e tráfego','Barbearia','Salão de beleza','Clínica','Loja','Imobiliária'];
export const id=()=>globalThis.crypto.randomUUID();
export const escapeHTML=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function phoneNumber(v){let n=String(v||'').replace(/\D/g,'');if(n.length===10||n.length===11)n='55'+n;return /^[1-9]\d{9,14}$/.test(n)?n:''}
export function freshWorkspace(){return {schemaVersion:3,leads:[],columns:[{id:'new',name:'Novo lead',limit:24,color:'#9b8afb'},{id:'service',name:'Em atendimento',limit:48,color:'#4d96d9'},{id:'waiting',name:'Aguardando resposta',limit:24,color:'#dfa04d'},{id:'closed',name:'Fechado',limit:0,color:'#46aa83'}],postSaleColumns:[{id:'onboarding',name:'Implantação',limit:168},{id:'adoption',name:'Adoção',limit:336},{id:'expansion',name:'Oportunidade',limit:168},{id:'renewal',name:'Renovação',limit:720}],cadence:defaultCadence(),reminders:[],notifications:[],whatsapp:{number:'',businessName:''},businessProfile:{niche:'',customNiche:'',onboarded:false},settings:{inactiveDays:30,recoveryDays:30},ai:{},manualApprovals:[]}}
export function defaultCadence(){return [2,24,48,72,120,168,240,336,504,720].map((delay,i)=>({id:'step-'+i,delay,unit:'horas',text:[ 'Oi, {nome}! Posso entender o que você está buscando neste momento?', '{nome}, ficou alguma dúvida sobre o que conversamos? Posso ajudar a esclarecer.', 'Qual seria o resultado mais importante para você agora?', 'Faz sentido uma ligação breve para entender o seu cenário?', 'Há alguma informação que faltou para você avaliar a proposta?', 'Posso apresentar um exemplo relacionado ao seu objetivo?', 'Vale reservarmos 15 minutos para definir um próximo passo?', 'Seu momento continua o mesmo ou alguma prioridade mudou?', 'Gostaria de retomar aquele objetivo ou prefere conversar mais adiante?', '{nome}, vou encerrar este acompanhamento por enquanto. Se quiser retomar, estou à disposição.' ][i]}))}
export function normalizeWorkspace(raw){
 const fresh=freshWorkspace(),s=raw&&typeof raw==='object'&&!Array.isArray(raw)?structuredClone(raw):{};
 const result={...fresh,...s,whatsapp:{...fresh.whatsapp,...s.whatsapp},businessProfile:{...fresh.businessProfile,...s.businessProfile},settings:{...fresh.settings,...s.settings},ai:s.ai&&typeof s.ai==='object'?s.ai:{}};
 for(const key of ['leads','columns','postSaleColumns','cadence','reminders','notifications','manualApprovals'])result[key]=Array.isArray(s[key])?s[key].filter(x=>x&&typeof x==='object'&&!Array.isArray(x)):fresh[key];
 for(const key of ['columns','postSaleColumns'])if(!result[key].length)result[key]=fresh[key];
 for(const c of Array.isArray(s.postSaleCustomers)?s.postSaleCustomers:[]){if(!c||!c.id||result.leads.some(l=>l.id==='post-'+c.id||l.id===c.leadId&&l.board==='Pós-venda'))continue;const linked=result.leads.find(l=>l.id===c.leadId);result.leads.push({...c,id:'post-'+c.id,name:c.name||c.company||'Cliente',phone:c.phone||linked?.phone||'',board:'Pós-venda',product:c.expansionProduct||c.product||'',contractValue:c.contractValue||0,notes:c.notes||'',messages:[],calls:[]})}
 result.leads=result.leads.map(l=>{const board=BOARDS.includes(l.board)?l.board:'Principal',cols=board==='Pós-venda'?result.postSaleColumns:result.columns;return {...l,id:String(l.id||id()),name:String(l.name||'Contato'),phone:String(l.phone||''),board,stage:cols.some(c=>c.id===l.stage)?l.stage:cols[0].id,messages:Array.isArray(l.messages)?l.messages.filter(Boolean):[],calls:Array.isArray(l.calls)?l.calls.filter(c=>c&&typeof c==='object'):[],notes:String(l.notes||''),entered:Number(l.entered)||Date.parse(l.entered)||Date.now()}});
 return result;
}
export function elapsed(since,now=Date.now()){const hours=Math.max(0,Math.floor((now-new Date(since).getTime())/3600000));return hours<1?'menos de 1h':hours<24?hours+'h':Math.floor(hours/24)+'d '+hours%24+'h'}
export function canContact(l){return !!l&&!l.optOut&&l.stage!=='closed'&&l.board!=='Pós-venda'}
export function callRecorded(l){return Array.isArray(l?.calls)&&l.calls.some(c=>c?.id&&c.at&&c.outcome&&!['agendada','cancelada','scheduled','planned','cancelled'].includes(String(c.outcome).toLowerCase())&&Number.isFinite(Date.parse(c.at))&&Date.parse(c.at)<=Date.now())}
export function nextDue(l,w,now=Date.now()){
 if(!canContact(l))return null;
 if(l.nextDate)return {at:new Date(l.nextDate).getTime(),type:l.nextAction||'Ligação',reason:'Agendamento'};
 if(l.automationPaused)return null;
 if(l.board==='Abandonados'){if(!l.discardReason||!l.recoveryAt)return null;return {at:new Date(l.recoveryAt).getTime(),type:'Revisar recuperação',reason:l.discardReason}}
 if(!callRecorded(l))return {at:l.entered,type:'Ligação',reason:'Primeiro contato'};
 if(l.cadenceEnabled){const step=w.cadence[l.cadenceIndex||0];if(step){const factor=/dia/.test(step.unit)?24:1;return {at:Number(l.cadenceStarted||l.entered)+Number(step.delay)*factor*3600000,type:step.action==='Ligar'?'Ligação':'Mensagem',reason:'Etapa '+((l.cadenceIndex||0)+1)}}}
 const last=new Date(l.lastContactAt||l.entered).getTime();
 if(l.board==='Principal'&&now-last>=Number(w.settings.inactiveDays||30)*86400000)return {at:last+Number(w.settings.inactiveDays||30)*86400000,type:'Retomar contato',reason:'Inativo'};
 if(l.stage==='waiting'){const col=w.columns.find(c=>c.id===l.stage);if(col?.limit===0)return null;return {at:Math.max(l.entered,Number(l.lastTaskCompletedAt)||0)+Number(col?.limit||24)*3600000,type:'Follow-up',reason:'Aguardando resposta'}}
 return null;
}
export function taskList(w,now=Date.now()){return w.leads.map(lead=>({lead,task:nextDue(lead,w,now)})).filter(x=>x.task&&Number.isFinite(x.task.at)).sort((a,b)=>a.task.at-b.task.at)}
export function suggestions(niche,l={}){const name=(l.name||'{nome}').split(' ')[0];const topic={'Barbearia':'corte, barba ou os dois','Salão de beleza':'corte, cor ou tratamento','Clínica':'sua avaliação inicial','Loja':'o produto e o prazo que você procura','Imobiliária':'a região, o orçamento e o prazo da busca','Marketing e tráfego':'sua oferta, público e objetivo com os anúncios'}[niche];return [topic?`Oi, ${name}! Posso entender melhor seu interesse em ${topic}?`:`Oi, ${name}! Qual resultado você procura e o que é prioridade agora?`,l.discardReason?`${name}, quando conversamos, você mencionou ${l.discardReason}. Esse cenário mudou ou prefere retomar em outro momento?`:`${name}, ficou alguma dúvida sobre ${l.product||'o que conversamos'}? Posso ajudar a definir o próximo passo.`,`${name}, faz sentido marcarmos uma conversa breve para entender ${l.needs||'o que você precisa'} e avaliar os próximos passos?` ]}
export function contextualTips(l){const tips=[];if(l.optOut)return ['Este contato pediu para não receber mensagens. Mantenha o acompanhamento pausado.'];if(!l.needs)tips.push('Pergunte: qual resultado você espera alcançar e por que isso importa agora?');if(!callRecorded(l))tips.push('Registre uma tentativa de ligação antes de preparar a primeira mensagem.');if(l.discardReason)tips.push('Confirme se o motivo do descarte ainda se aplica: '+l.discardReason+'.');if(l.product&&!l.contractValue)tips.push('Confirme escopo e expectativas antes de apresentar o investimento.');if(l.notes)tips.push('Use suas notas como contexto. Confirme com o cliente o que ainda estiver em aberto.');tips.push('Antes de sugerir uma reunião, confirme o objetivo, quem participa e a disponibilidade.');return tips.slice(0,4)}
export function messageData(m){return Array.isArray(m)?{direction:m[0],body:m[1],time:m[2],status:'registro anterior'}:m}
