const {chromium}=require('playwright');
const assert=require('node:assert/strict');

(async()=>{
 const browser=await chromium.launch(process.platform==='win32'&&!process.env.CI?{headless:true,channel:'msedge'}:{headless:true});
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 let metaReady=false,officialSends=0;
 await page.route('**/api/whatsapp?action=connection*',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,ready:metaReady,configured:metaReady,setup:{server_ready:true,credentials_saved:metaReady,meta_verified:metaReady,webhook_verified:metaReady},connection:metaReady?{business_number:'+55 11 91234-5678'}:null})}));
 await page.route('**/api/whatsapp?action=onboarding-status*',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({configuration:{ready:false},onboarding:{status:'idle'}})}));
 await page.route('**/api/whatsapp?action=messages*',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({messages:[],next_cursor:'0'})}));
 await page.route('**/api/whatsapp?action=send',route=>{officialSends++;return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true})})});
 await page.goto('http://127.0.0.1:8788');
 await page.locator('[data-auth-switch=true]').click();
 await page.locator('#auth-form [name=name]').fill('Vendedor Canal QA');
 await page.locator('#auth-form [name=company]').fill('Empresa Canal QA');
 await page.locator('[name=email]').fill('canal-'+Date.now()+'@example.test');
 await page.locator('[name=password]').fill('PulseFlow-local-2026!');
 await page.locator('#auth-form [name=legal_accepted]').check();
 await page.locator('#auth-form button[type=submit]').click();
 await page.locator('.sidebar').waitFor();
 if(await page.locator('#business-form').count()){
  await page.locator('#business-form [name=businessName]').fill('Empresa modos QA');
  await page.locator('#business-form button[type=submit]').click();
  assert.equal(await page.locator('#business-form').count(),1,'cadastro inicial exige número antes de começar');
  await page.locator('#business-form [name=number]').fill('11912345678');
  await page.locator('#business-form button[type=submit]').click();
  await page.locator('#modal').waitFor({state:'detached'});
 }
 await page.evaluate(()=>document.querySelector('.sidebar [data-page=settings]').click());
 await page.locator('[data-settings=channel]').click();
 await page.locator('.channel-choice-intro').waitFor();
 assert((await page.locator('.channel-choice-intro').innerText()).includes('Escolha como usar o WhatsApp'));
 assert((await page.locator('.manual-mode-guide').innerText()).includes('não sincroniza conversas'));
 assert((await page.locator('.meta-connect-card').innerText()).includes('custos aplicáveis da Meta'));
 assert(await page.evaluate(()=>document.querySelector('.manual-whatsapp-card').compareDocumentPosition(document.querySelector('.meta-connect-card'))&Node.DOCUMENT_POSITION_FOLLOWING));
 await page.locator('.manual-whatsapp-card [data-action=manual-number]').click();
 await page.locator('#manual-number-form [name=number]').fill('11987654321');
 await page.locator('#manual-number-form button[type=submit]').click();
 await page.locator('#modal').waitFor({state:'detached'});
 assert((await page.locator('.manual-whatsapp-card .number-card').innerText()).includes('5511987654321'));
 await page.evaluate(()=>document.querySelector('.sidebar [data-page=home]').click());
 await page.locator('[data-action=lead]').first().click();
 await page.locator('#lead-form [name=name]').fill('Resposta manual QA');
 await page.locator('#lead-form [name=phone]').fill('11923456789');
 await page.locator('#lead-form [name=consentConfirmed]').check();
 await page.locator('#lead-form button[type=submit]').click();
 await page.locator('#modal').waitFor({state:'detached'});
 await page.evaluate(()=>document.querySelector('.sidebar [data-page=conversations]').click());
 await page.locator('[data-action=manual-reply]').click();
 await page.locator('#manual-reply-form [name=text]').fill('Pode me ligar amanhã?');
 await page.locator('#manual-reply-form button[type=submit]').click();
 await page.locator('#modal').waitFor({state:'detached'});
 assert((await page.locator('.messages').innerText()).includes('Resposta registrada por você'));
 assert((await page.locator('.messages').innerText()).includes('Pode me ligar amanhã?'));
 const stored=await page.evaluate(async()=>{const me=await fetch('/api/auth?action=me').then(response=>response.json());return fetch('/api/auth?action=workspace&organization_id='+encodeURIComponent(me.account.id)).then(response=>response.json())});
 const lead=stored.workspace.leads.find(item=>item.name==='Resposta manual QA');
 assert.equal(stored.workspace.whatsapp.mode,'manual');
 assert.equal(lead.messages.at(-1).direction,'in');
 assert.equal(lead.messages.at(-1).status,'recorded_manual');
  assert.equal(lead.lastReplyId,lead.messages.at(-1).id);
 assert(lead.lastReplyAt);
 assert.equal(lead.automationPaused,true);
 await page.locator('[data-action=call]').first().click();
 await page.locator('#call-form button[type=submit]').click();
 await page.locator('#modal').waitFor({state:'detached'});
 metaReady=true;
 await page.reload();
 await page.locator('.sidebar').waitFor();
 await page.evaluate(()=>document.querySelector('.sidebar [data-page=conversations]').click());
 assert((await page.locator('#composer button[type=submit]').innerText()).includes('Abrir no WhatsApp'));
 assert((await page.locator('.chat-mode').innerText()).includes('API oficial continua sincronizando'));
 await page.evaluate(()=>{window.open=url=>{window.__manualOpened=url;return null}});
 await page.locator('#message-input').fill('Olá! Vamos conversar amanhã?');
 await page.locator('#composer button[type=submit]').click();
 await page.locator('.manual-confirm').waitFor();
 assert.match(await page.evaluate(()=>window.__manualOpened),/^https:\/\/wa\.me\/5511923456789\?text=/);
 assert.equal(officialSends,0);
 await page.locator('[data-action=confirm-manual]').click();
 await page.evaluate(()=>document.querySelector('.sidebar [data-page=settings]').click());
 await page.locator('[data-settings=channel]').click();
 await page.locator('[data-action=official-mode]').click();
 await page.evaluate(()=>document.querySelector('.sidebar [data-page=conversations]').click());
 assert((await page.locator('#composer button[type=submit]').innerText()).includes('Aprovar e enviar'));
 await page.locator('#message-input').fill('Mensagem oficial aprovada pelo vendedor.');
  const sendResponse=page.waitForResponse(response=>response.url().includes('/api/whatsapp?action=send'));
 await page.locator('#composer button[type=submit]').click();
  await sendResponse;
 await page.waitForFunction(()=>document.querySelector('#message-input')?.value==='');
 assert.equal(officialSends,1);
 assert.deepEqual(errors,[]);
 await browser.close();
 console.log('PASS: escolha manual/oficial, cadastro do número sem API, resposta recebida manual e envio wa.me mesmo com Meta pronta.');
})().catch(error=>{console.error(error);process.exit(1)});
