const {chromium}=require('playwright');
const assert=require('node:assert/strict');

(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 await page.goto('http://127.0.0.1:8788');
 await page.locator('[data-auth-switch=true]').click();
 await page.locator('[name=name]').fill('Automação QA');
 await page.locator('[name=company]').fill('Colunas QA '+Date.now());
 await page.locator('[name=email]').fill('columns-'+Date.now()+'@example.test');
 await page.locator('[name=password]').fill('PulseFlow-local-2026!');
 await page.locator('#auth-form [name=legal_accepted]').check();
 await page.locator('#auth-form button[type=submit]').click();
 await page.locator('.sidebar').waitFor();
 if(await page.locator('#business-form').count()){
  await page.locator('#business-form [name=number]').fill('11912345678');
  await page.locator('#business-form button[type=submit]').click();
  await page.locator('#modal').waitFor({state:'detached'});
 }
 await page.locator('.sidebar [data-page=automations]').click();
 assert.equal(await page.locator('.column-automation-list>article').count(),8);
 await page.locator('[data-automation-column="new"][data-column-board="Principal"]').click();
 assert(await page.locator('#column-form [name=observerEnabled]').isChecked());
 assert(await page.locator('#column-form [name=operatorEnabled]').isChecked());
 await page.locator('#column-form [name=automationEnabled]').check();
 await page.locator('[data-add-column-step]').click();
 await page.locator('[name="stepTrigger-0"]').selectOption('reply');
 await page.locator('[name="stepDelay-0"]').fill('2');
 await page.locator('[name="stepUnit-0"]').selectOption('horas');
 await page.locator('[name="stepAction-0"]').selectOption('message');
 await page.locator('[name="stepText-0"]').fill('Oi, {nome}! Vamos retomar {produto}?');
 await page.locator('#column-form button[type=submit]').click();
 await page.locator('#modal').waitFor({state:'detached'});
 const newColumn=page.locator('[data-automation-column="new"][data-column-board="Principal"]').locator('..');
 assert((await newColumn.innerText()).includes('1 ações'));
 await page.locator('[data-automation-column="new"][data-column-board="Principal"]').click();
 await page.locator('[data-add-column-step]').click();
 await page.locator('[name="stepTrigger-1"]').selectOption('deadline');
 await page.locator('[name="stepAction-1"]').selectOption('notify');
 await page.locator('[name="stepText-1"]').fill('Revisar contexto do contato.');
 await page.locator('#column-form button[type=submit]').click();
 await page.locator('#modal').waitFor({state:'detached'});
 await page.locator('[data-automation-column="new"][data-column-board="Principal"]').click();
 const stepIds=await page.locator('[data-column-step]').evaluateAll(rows=>rows.map(row=>row.dataset.stepId));
 assert.equal(stepIds.length,2);assert(stepIds.every(Boolean));
 await page.locator('[data-column-step]').nth(1).locator('textarea').fill('Orientação alterada com segurança.');
 await page.locator('#column-form button[type=submit]').click();
 await page.locator('#modal').waitFor({state:'detached'});
 await page.locator('[data-automation-column="new"][data-column-board="Principal"]').click();
 const editedStepIds=await page.locator('[data-column-step]').evaluateAll(rows=>rows.map(row=>row.dataset.stepId));
 assert.equal(editedStepIds[0],stepIds[0]);assert.notEqual(editedStepIds[1],stepIds[1]);
 await page.locator('[data-column-step]').first().locator('[data-remove-column-step]').click();
 await page.locator('#column-form button[type=submit]').click();
 await page.locator('#modal').waitFor({state:'detached'});
 await page.locator('[data-automation-column="new"][data-column-board="Principal"]').click();
 assert.equal(await page.locator('[data-column-step]').count(),1);
 assert.equal(await page.locator('[data-column-step]').getAttribute('data-step-id'),editedStepIds[1]);
 await page.getByRole('button',{name:'Cancelar',exact:true}).click();
 await page.locator('.sidebar [data-page=leads]').click();
 assert((await page.locator('[data-column="new"] .column-agent-summary').innerText()).includes('1 ações'));
 await page.locator('.sidebar [data-page=automations]').click();
 await page.locator('[data-column-board="Pós-venda"]').first().click();
 assert((await page.locator('#column-form').innerText()).includes('Pós-venda somente observacional'));
 assert.equal(await page.locator('#column-form [name=operatorEnabled]').count(),0);
 assert.equal(await page.locator('#column-form [data-add-column-step]').count(),0);
 await page.getByRole('button',{name:'Cancelar',exact:true}).click();
 await page.setViewportSize({width:360,height:844});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.locator('[data-automation-column="new"][data-column-board="Principal"]').click();
 assert(await page.evaluate(()=>{const modal=document.querySelector('#modal');return modal.scrollWidth<=modal.clientWidth+1}));
 await page.getByRole('button',{name:'Cancelar',exact:true}).click();
 await page.setViewportSize({width:1280,height:900});
 await page.locator('.sidebar [data-page=leads]').click();
 const columnsBefore=await page.locator('.kanban-column').count();
 await page.locator('[data-action=column]').click();
 await page.locator('#column-form [name=name]').fill('Não deve ficar fantasma');
 await page.locator('[data-add-column-step]').click();
 await page.locator('#column-form button[type=submit]').click();
 assert(await page.locator('#column-form').isVisible());
 assert((await page.locator('#column-form .form-error').innerText()).includes('Escreva a mensagem'));
 await page.getByRole('button',{name:'Cancelar',exact:true}).click();
 assert.equal(await page.locator('.kanban-column').count(),columnsBefore);
 assert.deepEqual(errors,[]);
 console.log('PASS: automações por coluna, gatilhos, aprovação manual, pós-venda observacional e mobile.');
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
