const {chromium,request}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8788');
 const loginCopy=await page.locator('.auth-card').innerText();assert(loginCopy.includes('Versão de lançamento'));assert(loginCopy.includes('R$ 9,90'));assert(loginCopy.includes('referência'));assert(loginCopy.includes('Cobrança online ainda não disponível'));assert(!loginCopy.includes('7 dias para conhecer'));
 const legalPage=await context.newPage();await legalPage.goto('http://127.0.0.1:8788/#termos');assert((await legalPage.locator('.legal-page').innerText()).includes('Termos de Uso'));await legalPage.goto('http://127.0.0.1:8788/#privacidade');const policyText=await legalPage.locator('.legal-page').innerText();assert(policyText.includes('Política de Privacidade'));assert(policyText.includes('formulário público de privacidade'));assert(!policyText.includes('em até 30 dias'));assert.equal(await legalPage.locator('a[href="/#exclusao-de-dados"]').count(),2);
 const deletionPage=await context.newPage();let privacyPayload;const protocol='00000000-0000-4000-8000-000000000001';await deletionPage.route('**/api/auth?action=privacy-request-public',route=>{privacyPayload=route.request().postDataJSON();return route.fulfill({status:201,contentType:'application/json',body:JSON.stringify({ok:true,protocol,message:'Solicitação registrada.'})})});
 await deletionPage.goto('http://127.0.0.1:8788/#exclusao-de-dados');const deletionText=await deletionPage.locator('.legal-page').innerText();assert(deletionText.includes('Exclusão de dados'));assert(deletionText.includes('Apps e sites'));assert(deletionText.includes('Não apaga dados'));assert(!deletionText.includes('em até 30 dias'));assert(!deletionText.includes('em até 90 dias'));
 await deletionPage.locator('#privacy-request-public-form [name=email]').fill('privacidade@example.test');await deletionPage.locator('#privacy-request-public-form [name=company]').fill('Empresa QA');await deletionPage.locator('#privacy-request-public-form [name=scope]').selectOption('organization');await deletionPage.locator('#privacy-request-public-form [name=details]').fill('Solicito avaliação dos dados da empresa.');await deletionPage.locator('#privacy-request-public-form button[type=submit]').click();await deletionPage.locator('#privacy-request-result').waitFor();assert.deepEqual(privacyPayload,{email:'privacidade@example.test',company:'Empresa QA',scope:'organization',details:'Solicito avaliação dos dados da empresa.'});assert((await deletionPage.locator('#privacy-request-result').innerText()).includes(protocol));assert((await deletionPage.locator('#privacy-request-result').innerText()).includes('nenhum dado foi excluído automaticamente'));await deletionPage.close();await legalPage.close();
 await page.locator('[data-auth-switch=true]').click();await page.locator('[name=name]').fill('Vendedor QA');await page.locator('[name=company]').fill('Empresa QA '+Date.now());await page.locator('[name=email]').fill('qa-'+Date.now()+'@example.test');await page.locator('[name=password]').fill('PulseFlow-local-2026!');await page.locator('#auth-form [name=legal_accepted]').check();await page.locator('#auth-form button[type=submit]').click();
 await page.locator('.sidebar').waitFor();
 if(await page.locator('#modal').count()){await page.locator('#modal [name=number]').fill('11912345678');await page.locator('#modal [name=niche]').selectOption('Barbearia');await page.locator('#modal button[type=submit]').click();await page.locator('#modal').waitFor({state:'detached'})}
 await page.screenshot({path:'tests/desktop.png',fullPage:true});
 for(let i=0;i<10;i++){await page.locator('[data-action=lead]').first().click();assert(await page.locator('#modal').isVisible());if(i%2)await page.getByRole('button',{name:'Cancelar',exact:true}).click();else await page.getByRole('button',{name:'Fechar janela'}).click();await page.locator('#modal').waitFor({state:'detached'});}
 await page.locator('[data-action=lead]').first().click();await page.locator('#lead-form [name=name]').fill('Contato QA');await page.locator('#lead-form [name=phone]').fill('11923456789');await page.locator('#lead-form details.advanced>summary').first().click();await page.locator('#lead-form [name=assigneeId]').selectOption({index:1});await page.locator('[name=consentConfirmed]').check();await page.locator('#lead-form button[type=submit]').click();await page.locator('#modal').waitFor({state:'detached'});
 await page.locator('.sidebar [data-page=leads]').click();assert((await page.locator('.lead-card .pill.green').innerText()).includes('Vendedor QA'));await page.locator('.sidebar [data-page=conversations]').click();assert(await page.locator('#message-input').isDisabled());await page.locator('[data-action=call]').first().click();await page.locator('#call-form [name=note]').fill('Quer um corte na sexta-feira.');await page.locator('#call-form button[type=submit]').click();await page.locator('#modal').waitFor({state:'detached'});assert(await page.locator('#message-input').isEnabled());
 await page.locator('[data-template="0"]').click();assert((await page.locator('#message-input').inputValue()).includes('corte'));
 await page.screenshot({path:'tests/conversation.png',fullPage:true});
 await context.route('https://wa.me/**',route=>route.fulfill({status:200,body:'External WhatsApp suppressed in local test.'}));
 await page.locator('#composer button[type=submit]').click();await page.locator('.manual-confirm').waitFor();assert.equal(await page.locator('.messages .outgoing').count(),0);await page.locator('[data-action=confirm-manual]').click();assert.equal(await page.locator('.messages .outgoing').count(),1);assert((await page.locator('.messages').innerText()).includes('Envio confirmado por você'));
 const futureDate=new Date();futureDate.setDate(futureDate.getDate()+7);futureDate.setHours(14,0,0,0);const futureDateTime=`${futureDate.getFullYear()}-${String(futureDate.getMonth()+1).padStart(2,'0')}-${String(futureDate.getDate()).padStart(2,'0')}T14:00`;
 await page.locator('[data-action=schedule]').click();await page.locator('#schedule-form [name=nextDate]').fill(futureDateTime);await page.locator('#schedule-form button[type=submit]').click();await page.locator('#modal').waitFor({state:'detached'});await page.reload();await page.locator('.sidebar').waitFor();
 for(const pageName of ['home','leads','conversations','agenda','automations','settings']){await page.locator('.sidebar [data-page='+pageName+']').click();assert(await page.locator('.page').isVisible());}
 await page.locator('.sidebar [data-page=agenda]').click();await page.locator('[data-agenda=upcoming]').click();assert.match(await page.locator('.agenda-actions a').getAttribute('href'),/^https:\/\/calendar\.google\.com\//);assert.equal(await page.locator('[data-calendar]').count(),1);
 await page.locator('.alert-button').click();assert((await page.locator('#modal').innerText()).includes('Alertas e próximas ações'));await page.getByRole('button',{name:'Fechar',exact:true}).click();await page.locator('#modal').waitFor({state:'detached'});
 await page.locator('.sidebar [data-page=automations]').click();assert((await page.locator('.automation-hero').innerText()).includes('Agente PulseFlow'));await page.locator('#agent-form [name=enabled]').check();await page.locator('#agent-form [name=learningEnabled]').check();await page.locator('#agent-form [name=name]').fill('Agente Empresa QA');await page.locator('#agent-form button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('.automation-hero')?.innerText.includes('Agente Empresa QA'));await page.locator('[data-action=automation-rule]').click();await page.locator('#automation-form [name=name]').fill('Regra QA');await page.locator('#automation-form button[type=submit]').click();await page.locator('#modal').waitFor({state:'detached'});assert((await page.locator('.automation-rules').innerText()).includes('Regra QA'));await page.screenshot({path:'tests/automations.png',fullPage:true});
 await page.locator('.sidebar [data-page=conversations]').click();await page.locator('[data-ai-action=analyze]').click();await page.waitForFunction(()=>document.querySelector('.ai-insight')?.innerText.includes('REVISÃO OBRIGATÓRIA'));assert((await page.locator('.ai-insight').innerText()).includes('nada foi enviado automaticamente'));await page.locator('[data-ai-action=use]').click();assert((await page.locator('#message-input').inputValue()).includes('sexta-feira'));await page.screenshot({path:'tests/ai-analysis.png',fullPage:true});
 await page.locator('.sidebar [data-page=settings]').click();await page.locator('[data-settings=plan]').click();assert((await page.locator('.plans').innerText()).includes('9,90'));assert((await page.locator('.settings-content').innerText()).includes('A cobrança online ainda não está conectada.'));
 await page.locator('[data-settings=security]').click();await page.waitForFunction(()=>document.querySelector('.team-list'));assert((await page.locator('.settings-content').innerText()).includes('O plano Base é individual'));await page.locator('[data-action=password]').click();assert.equal(await page.locator('#password-form').count(),1);await page.getByRole('button',{name:'Cancelar',exact:true}).click();await page.locator('#modal').waitFor({state:'detached'});assert((await page.locator('.settings-content').innerText()).includes('Integração com outros sistemas'));assert.equal(await page.locator('[data-action=export-leads]').count(),1);await page.locator('#integration-api-panel [data-action=integration-key]').click();await page.locator('#integration-key-form [name=name]').fill('CRM de teste');await page.locator('#integration-key-form [value="contacts:write"]').check();await page.locator('#integration-key-form button[type=submit]').click();await page.locator('#integration-api-key').waitFor();assert.match(await page.locator('#integration-api-key').inputValue(),/^pfk_/);await page.keyboard.press('Escape');assert(await page.locator('#integration-api-key').isVisible());await page.getByRole('button',{name:'Já copiei e salvei',exact:true}).click();await page.locator('#modal').waitFor({state:'detached'});assert((await page.locator('#integration-api-panel').innerText()).includes('CRM de teste'));assert((await page.locator('#integration-api-panel').innerText()).includes('Criar e atualizar contatos'));assert.equal(await page.locator('#integration-api-key').count(),0);page.once('dialog',dialog=>dialog.accept());await page.locator('#integration-api-panel [data-revoke-key]').click();await page.waitForFunction(()=>!document.querySelector('#integration-api-panel [data-revoke-key]'));await page.locator('#crm-import').setInputFiles({name:'contatos.csv',mimeType:'text/csv',buffer:Buffer.from('nome;whatsapp;origem;interesse;pipeline;etapa\nContato CSV;11987654321;Outro CRM;Alta;Principal;Novo Lead')});await page.waitForFunction(()=>document.body.innerText.includes('1 contatos importados'));
 const me=await page.evaluate(()=>fetch('/api/auth?action=me').then(r=>r.json())),adminApi=await request.newContext({baseURL:'http://127.0.0.1:8788'});await adminApi.post('/api/auth?action=login',{headers:{Origin:'http://127.0.0.1:8788'},data:{email:'admin@example.test',password:'PulseFlow-local-2026!'}});assert.equal((await adminApi.post('/api/auth?action=admin-account',{headers:{Origin:'http://127.0.0.1:8788'},data:{organization_id:me.account.id,plan:'Equipe'}})).status(),200);await adminApi.dispose();await page.reload();await page.locator('.sidebar').waitFor();await page.locator('.sidebar [data-page=settings]').click();await page.locator('[data-settings=security]').click();await page.waitForFunction(()=>document.querySelector('[data-action=member]'));await page.locator('[data-action=member]').click();const inviteEmail='invite-'+Date.now()+'@example.test';await page.locator('#member-form [name=name]').fill('Vendedor convidado');await page.locator('#member-form [name=email]').fill(inviteEmail);await page.locator('#member-form button[type=submit]').click();await page.locator('#team-invite-url').waitFor();const inviteUrl=await page.locator('#team-invite-url').inputValue();assert.match(inviteUrl,/#invite=/);const inviteContext=await browser.newContext({viewport:{width:390,height:844}}),invitePage=await inviteContext.newPage();await invitePage.goto(inviteUrl);await invitePage.locator('#invite-form [name=password]').fill('Invite-only-Password!');await invitePage.locator('#invite-form [name=legal_accepted]').check();await invitePage.locator('#invite-form button[type=submit]').click();await invitePage.locator('.sidebar').waitFor();assert((await invitePage.locator('.workspace-label').innerText()).includes('Empresa QA'));await inviteContext.close();await page.getByRole('button',{name:'Fechar',exact:true}).click();
 await page.locator('[data-settings=operation]').click();await page.locator('[data-action=cadence]').click();assert.equal(await page.locator('#cadence-form textarea').count(),10);
 await page.setViewportSize({width:390,height:844});await page.locator('.mobile-nav [data-page=home]').click();await page.screenshot({path:'tests/mobile.png',fullPage:true});
 for(const width of [360,390,430]){await page.setViewportSize({width,height:844});for(const pageName of ['home','leads','conversations','agenda','automations']){await page.locator('.mobile-nav [data-page='+pageName+']').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Overflow '+pageName+' '+width);}await page.evaluate(()=>document.querySelector('.sidebar [data-page=settings]').click());await page.locator('[data-settings=security]').click();await page.locator('#integration-api-panel').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Overflow settings '+width);}
 await page.screenshot({path:'tests/mobile-agenda.png',fullPage:true});
 const privacyAdminProtocol='00000000-0000-4000-8000-000000000001';let privacyAdminStatus='pending',privacyAdminOperation;
 await page.route('**/api/auth?action=admin-privacy-requests',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,requests:[{id:privacyAdminProtocol,organization_id:null,source:'public',scope:'organization',contact_email:'privacidade@example.test',organization_name:'Empresa QA',details:'Solicito avaliação dos dados da empresa.',status:privacyAdminStatus,identity_verified_at:privacyAdminStatus==='verified'?'2026-10-03T11:00:00Z':null,created_at:'2026-10-03T10:00:00Z'}]})}));
 await page.route('**/api/auth?action=admin-privacy-request',route=>{privacyAdminOperation=route.request().postDataJSON();privacyAdminStatus='verified';return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true})})});
 await page.setViewportSize({width:1440,height:1000});await page.locator('.sidebar [data-action=logout]').click();await page.locator('[name=email]').fill('admin@example.test');await page.locator('[name=password]').fill('PulseFlow-local-2026!');await page.locator('#auth-form button[type=submit]').click();await page.locator('[data-support]').first().waitFor();await page.locator('#admin-privacy-requests').waitFor();assert((await page.locator('#admin-privacy-requests').innerText()).includes('Nenhuma operação exclui dados automaticamente'));await page.locator('[data-privacy-open]').first().click();assert((await page.locator('#modal').innerText()).includes(privacyAdminProtocol));assert((await page.locator('#modal').innerText()).toLowerCase().includes('não exclui dados'));await page.locator('#privacy-admin-form [name=operation]').selectOption('verify');await page.locator('#privacy-admin-form [name=note]').fill('Identidade confirmada com o proprietário.');await page.locator('#privacy-admin-form button[type=submit]').click();await page.locator('#modal').waitFor({state:'detached'});assert.deepEqual(privacyAdminOperation,{request_id:privacyAdminProtocol,operation:'verify',note:'Identidade confirmada com o proprietário.'});await page.waitForFunction(()=>document.querySelector('#admin-privacy-requests')?.innerText.includes('Identidade verificada'));await page.screenshot({path:'tests/admin.png',fullPage:true});page.once('dialog',dialog=>dialog.accept());await page.locator('[data-reset-user]').first().click();await page.locator('#admin-reset-url').waitFor();assert.match(await page.locator('#admin-reset-url').inputValue(),/#reset=/);await page.getByRole('button',{name:'Fechar',exact:true}).click();await page.locator('#modal').waitFor({state:'detached'});await page.locator('[data-support]').first().click();await page.locator('.support-banner').waitFor();await page.locator('.support-banner [data-action=exit-support]').click();await page.locator('[data-support]').first().waitFor();
 assert.deepEqual(errors,[]);console.log('PASS: login, onboarding, 10 closes, assigned lead, call-first, templates, agenda persistence, six pages, agent automation, secure team invitation, admin password reset, CRM CSV bridge, plans, cadence, 390px navigation, admin/support.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
