const {chromium,request}=require('playwright');
const assert=require('node:assert/strict');

(async()=>{
 const launchOptions={headless:true};
 if(process.platform==='win32'&&!process.env.CI)launchOptions.channel='msedge';
 const browser=await chromium.launch(launchOptions);
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 await page.addInitScript(()=>{window.FB={init:function(){},login:function(callback,options){window.__fbLogin=callback;window.__fbOptions=options;}}});
 let metaStatus='idle',metaStarts=0,metaConfigurationReady=false;
 await page.route('https://connect.facebook.net/pt_BR/sdk.js',route=>route.fulfill({status:200,contentType:'application/javascript',body:`window.FB={init:function(){},login:function(callback,options){window.__fbLogin=callback;window.__fbOptions=options;}};if(window.fbAsyncInit)window.fbAsyncInit();`}));
 await page.route('**/api/whatsapp?action=connection*',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(metaStatus==='connected'?{ok:true,ready:true,configured:true,setup:{server_ready:true,credentials_saved:true,meta_verified:true,webhook_verified:true},connection:{business_number:'+55 11 91234-5678'}}:{ok:true,ready:false,configured:false,setup:{server_ready:true,credentials_saved:false,meta_verified:false,webhook_verified:false},connection:null})}));
 await page.route('**/api/whatsapp?action=onboarding-status*',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({configuration:{ready:metaConfigurationReady,app_id:'123456789012345',config_id:'987654321098765',graph_version:'v23.0'},onboarding:{status:metaStatus},connection:metaStatus==='connected'?{ready:true,business_number:'+55 11 91234-5678'}:null})}));
 await page.route('**/api/whatsapp?action=onboarding-start*',route=>{metaStarts++;metaStatus='pending';return route.fulfill({status:201,contentType:'application/json',body:JSON.stringify({flow_id:'11111111-1111-4111-8111-111111111111',state:'state-for-ui-test-123456789012345678901234567890',app_id:'123456789012345',config_id:'987654321098765',graph_version:'v23.0'})})});
 await page.route('**/api/whatsapp?action=onboarding-callback*',route=>{metaStatus='connected';return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,connection:{ready:true,business_number:'+55 11 91234-5678'}})});});
 await page.goto('http://127.0.0.1:8788');
 await page.locator('[name=email]').fill('seller@example.test');
 await page.locator('[name=password]').fill('PulseFlow-local-2026!');
 await page.locator('#auth-form button[type=submit]').click();
 await page.locator('.sidebar').waitFor();
 if(await page.locator('#business-form').count()){
  await page.locator('#business-form [name=businessName]').fill('Empresa webhook QA');
  await page.locator('#business-form [name=number]').fill('11912345678');
  await page.locator('#business-form button[type=submit]').click();
  await page.locator('#modal').waitFor({state:'detached'});
 }

 const me=await page.evaluate(()=>fetch('/api/auth?action=me').then(response=>response.json()));
 const adminApi=await request.newContext({baseURL:'http://127.0.0.1:8788'});
 await adminApi.post('/api/auth?action=login',{headers:{Origin:'http://127.0.0.1:8788'},data:{email:'admin@example.test',password:'PulseFlow-local-2026!'}});
 const resetPlan=await adminApi.post('/api/auth?action=admin-account',{headers:{Origin:'http://127.0.0.1:8788'},data:{organization_id:me.account.id,plan:'Base'}});
 assert.equal(resetPlan.status(),200);
 await page.reload();
 await page.locator('.sidebar').waitFor();

 await page.locator('.sidebar [data-page=settings]').click();
 const metaStatusResponse=page.waitForResponse(response=>response.url().includes('action=onboarding-status'));
 await page.locator('[data-settings=channel]').click();
 await metaStatusResponse;
 const metaPanel=page.locator('.meta-connect-card');
 await metaPanel.waitFor();
 assert.equal(await metaPanel.getAttribute('data-meta-state'),'unavailable');
 assert((await metaPanel.innerText()).includes('Configuração da plataforma pendente.'));
 assert.equal((await metaPanel.innerText()).includes('Pronto para conectar'),false);
 assert.equal(await metaPanel.getByRole('button',{name:'Configuração pendente',exact:true}).isDisabled(),true);
 metaConfigurationReady=true;
 await page.locator('[data-settings=business]').click();
 const configuredStatusResponse=page.waitForResponse(response=>response.url().includes('action=onboarding-status'));
 await page.locator('[data-settings=channel]').click();
 await configuredStatusResponse;
 await page.waitForFunction(()=>document.querySelector('.meta-connect-card')?.dataset.metaState==='idle');
 assert((await metaPanel.innerText()).includes('Conecte seu WhatsApp com a Meta'));
 assert((await metaPanel.innerText()).includes('sem QR Code'));
 assert.equal(await page.locator('.meta-advanced').getAttribute('open'),null,'Credenciais técnicas devem começar recolhidas.');
 assert.equal(await page.locator('.meta-advanced [name=access_token]').isVisible(),false,'Token manual não deve aparecer no fluxo simples.');
 await metaPanel.locator('[data-action=meta-connect]').click();
 await page.waitForFunction(()=>document.querySelector('.meta-connect-card')?.dataset.metaState==='pending');
 assert.equal(metaStarts,1);
 await page.waitForFunction(()=>window.__fbOptions?.config_id==='987654321098765');
 assert((await metaPanel.innerText()).includes('Conclua a autorização na janela da Meta'));
 await page.evaluate(()=>{
  const embedded={type:'WA_EMBEDDED_SIGNUP',event:'FINISH',data:{waba_id:'123456789012345',phone_number_id:'234567890123456'}};
  window.dispatchEvent(new MessageEvent('message',{origin:'https://www.facebook.com',data:JSON.stringify(embedded)}));
  window.__fbLogin({authResponse:{code:'meta-code-for-ui-test-123456789'}});
 });
 await page.waitForFunction(()=>document.querySelector('.meta-connect-card')?.dataset.metaState==='connected');
 assert((await metaPanel.innerText()).includes('+55 11 91234-5678'));
 await page.locator('.meta-advanced>summary').click();
 assert(await page.locator('.meta-advanced [name=access_token]').isVisible());
 await page.setViewportSize({width:390,height:844});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Conexão Meta não deve causar overflow no mobile.');
 await page.setViewportSize({width:1280,height:900});
 let loaded=page.waitForResponse(response=>response.url().includes('action=webhooks'));
 await page.locator('[data-settings=security]').click();
 await loaded;
 assert.equal(await page.locator('#outbound-webhooks-panel').count(),0,'Plano Base sem destinos não deve exibir webhooks avançados.');

 const upgrade=await adminApi.post('/api/auth?action=admin-account',{headers:{Origin:'http://127.0.0.1:8788'},data:{organization_id:me.account.id,plan:'Equipe'}});
 assert.equal(upgrade.status(),200);
 await adminApi.dispose();

 await page.reload();
 await page.locator('.sidebar').waitFor();
 await page.locator('.sidebar [data-page=settings]').click();
 loaded=page.waitForResponse(response=>response.url().includes('action=webhooks'));
 await page.locator('[data-settings=security]').click();
 await loaded;
 const panel=page.locator('#outbound-webhooks-panel');
 await panel.waitFor();
 assert.equal(await panel.getAttribute('open'),null,'O painel deve iniciar recolhido.');
 await panel.locator('summary').click();
 await panel.locator('[data-action=outbound-webhook]').click();
 assert.equal(await page.locator('#outbound-webhook-form [name=event_types]').count(),6);
 assert((await page.locator('#outbound-webhook-form').innerText()).includes('somente IDs e horário'));
 await page.locator('#outbound-webhook-form [name=name]').fill('ERP financeiro');
 await page.locator('#outbound-webhook-form [name=url]').fill('https://hooks.example.test/pulseflow/clientes');
 await page.locator('#outbound-webhook-form button[type=submit]').click();
 const secretField=page.locator('#outbound-webhook-secret');
 await secretField.waitFor();
 const secret=await secretField.inputValue();
 assert.match(secret,/^whsec_/);
 await page.keyboard.press('Escape');
 assert(await secretField.isVisible(),'O segredo one-time não pode sumir com Escape.');
 await page.getByRole('button',{name:'Já copiei e salvei',exact:true}).click();
 await page.locator('#modal').waitFor({state:'detached'});
 assert.equal((await page.content()).includes(secret),false,'O segredo não deve permanecer no DOM.');
 assert((await panel.innerText()).includes('ERP financeiro'));
 assert((await panel.innerText()).includes('hooks.example.test'));
 assert.equal((await panel.innerText()).includes('/pulseflow/clientes'),false,'O caminho completo do destino não deve ser exibido.');

 await panel.locator('[data-test-webhook]').click();
 await page.waitForFunction(()=>document.body.innerText.includes('Teste colocado na fila de entrega.'));
 assert(await panel.getAttribute('open')!==null);
 page.once('dialog',dialog=>dialog.accept());
 await panel.locator('[data-revoke-webhook]').click();
 await page.waitForFunction(()=>document.querySelectorAll('[data-revoke-webhook]').length===0);
 assert((await panel.innerText()).includes('Nenhum webhook cadastrado.'));

 await page.setViewportSize({width:390,height:844});
 await panel.locator('summary').click();
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Webhooks não devem causar overflow no mobile.');
 assert.deepEqual(errors,[]);
 console.log('PASS: webhooks de saída ocultos no Base, criação segura, segredo one-time, teste enfileirado, revogação e mobile.');
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
